export const storedRecipe = [
  {
    id: 1,
    recipeName: "Gyu Don",
    origin: "Japan",
    dateCreated: "17/04/25",
    ingridients: "",
    steps: "",
    rating: "8/10",
  },
  {
    id: 2,
    recipeName: "Lasagne",
    origin: "Italian",
    dateCreated: "21/04/25",
    ingridients: "",
    steps: "",
    rating: "7/10",
  },
  {
    id: 3,
    recipeName: "Tacos al Pastor",
    origin: "Mexico",
    dateCreated: "19/04/25",
    ingridients: "",
    steps: "",
    rating: "9/10",
  },
  {
    id: 4,
    recipeName: "Pad Thai",
    origin: "Thailand",
    dateCreated: "15/04/25",
    ingridients: "",
    steps: "",
    rating: "8/10",
  },
  {
    id: 5,
    recipeName: "Butter Chicken",
    origin: "India",
    dateCreated: "20/04/25",
    ingridients: "",
    steps: "",
    rating: "9/10",
  },
  {
    id: 6,
    recipeName: "Beef Wellington",
    origin: "United Kingdom",
    dateCreated: "18/04/25",
    ingridients: "",
    steps: "",
    rating: "8/10",
  },
  {
    id: 7,
    recipeName: "Pho",
    origin: "Vietnam",
    dateCreated: "16/04/25",
    ingridients: "",
    steps: "",
    rating: "7/10",
  },
  {
    id: 8,
    recipeName: "Croque Monsieur",
    origin: "France",
    dateCreated: "14/04/25",
    ingridients: "",
    steps: "",
    rating: "6/10",
  },
  {
    id: 9,
    recipeName: "Shakshuka",
    origin: "Middle East",
    dateCreated: "13/04/25",
    ingridients: "",
    steps: "",
    rating: "8/10",
  },
  {
    id: 10,
    recipeName: "Bibimbap",
    origin: "Korea",
    dateCreated: "12/04/25",
    ingridients: "",
    steps: "",
    rating: "9/10",
  },
];
[
  {
    _id: "680c23b9a33814e78df9b6a3",
    recipeName: "Gyu Don",
    origin: "Japan",
    dateCreated: "17/04/25",
    ingridients: "",
    steps: "",
    rating: "8/10",
  },
  {
    _id: "680c23b9a33814e78df9b6a4",
    recipeName: "Lasagne",
    origin: "Italian",
    dateCreated: "21/04/25",
    ingridients: "",
    steps: "",
    rating: "7/10",
  },
  {
    _id: "680c23b9a33814e78df9b6a5",
    recipeName: "Tacos al Pastor",
    origin: "Mexico",
    dateCreated: "19/04/25",
    ingridients: "",
    steps: "",
    rating: "9/10",
  },
  {
    _id: "680c23b9a33814e78df9b6a6",
    recipeName: "Pad Thai",
    origin: "Thailand",
    dateCreated: "15/04/25",
    ingridients: "",
    steps: "",
    rating: "8/10",
  },
  {
    _id: "680c23b9a33814e78df9b6a7",
    recipeName: "Butter Chicken",
    origin: "India",
    dateCreated: "20/04/25",
    ingridients: "",
    steps: "",
    rating: "9/10",
  },
  {
    _id: "680c23b9a33814e78df9b6a8",
    recipeName: "Beef Wellington",
    origin: "United Kingdom",
    dateCreated: "18/04/25",
    ingridients: "",
    steps: "",
    rating: "8/10",
  },
  {
    _id: "680c23b9a33814e78df9b6a9",
    recipeName: "Pho",
    origin: "Vietnam",
    dateCreated: "16/04/25",
    ingridients: "",
    steps: "",
    rating: "7/10",
  },
  {
    _id: "680c23b9a33814e78df9b6aa",
    recipeName: "Croque Monsieur",
    origin: "France",
    dateCreated: "14/04/25",
    ingridients: "",
    steps: "",
    rating: "6/10",
  },
];
